core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('finanzas/', include('finanzas.urls')),
    path('', views.home),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.error_403_view

core/finanzas/urls.py
from django.urls import path
from . import views
from .views import eliminar_medio_pago, eliminar_categoria  # Asegúrate de importar la vista


app_name = 'finanzas'
urlpatterns = [
    path('', views.home_finanzas, name='home'),
    path('movimientos/', views.lista_movimientos, name='lista_movimientos'),
    path('movimientos/crear/', views.crear_movimiento, name='crear_movimiento'),
    path('categorias/crear/', views.crear_categoria, name='crear_categoria'),
    path('mediosdepago/crear/', views.crear_mediopago, name='crear_mediodepago'),
    path('mediopago/eliminar/<int:medio_pago_id>/', eliminar_medio_pago, name='eliminar_medio_pago'),
    path('categorias/eliminar/<int:id>/', eliminar_categoria, name='eliminar_categoria'), 
    path('movimientos/detalle/<int:id>/', views.detalle_movimiento, name='detalle_movimiento'),
    path('mediopagos/detalle/<int:medio_pago_id>/', views.detalle_medio_pago, name='detalle_medio_pago'),
    path('actualizar-cotizacion/', views.actualizar_cotizacion, name='actualizar_cotizacion'),
    path('eliminar-movimiento/<int:movimiento_id>/', views.eliminar_movimiento, name='eliminar_movimiento'),
    path('movimientos/editar/<int:movimiento_id>/', views.editar_movimiento, name='editar_movimiento'),  
    path('documento-adjunto/<int:documento_id>/eliminar/', views.eliminar_documento_adjunto, name='eliminar_documento_adjunto'),


]

core/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Gestión de Flipping Cars</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <!-- Enlazando el archivo CSS global -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="{% static 'css/global.css' %}" rel="stylesheet">
    <link href="{% static 'css/finanzas.css' %}" rel="stylesheet">
</head>
<body>
    <!-- Incluir Sidebar -->
    {% include 'sidebar.html' %}

    <!-- Incluir Navbar -->
    {% include 'navbar.html' %}

    <!-- Contenido Principal -->
    <div class="main-content">
        {% block content %}
        <!-- Este bloque será sobreescrito por otras plantillas que extiendan base.html -->
        {% endblock %}
    </div>
    {% if messages %}
    <div aria-live="polite" aria-atomic="true" class="position-relative" style="z-index: 1000;">
      <div class="toast-container position-fixed bottom-0 end-0 p-3">
        {% for message in messages %}
        <div class="toast align-items-center text-white bg-{{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
          <div class="d-flex">
            <div class="toast-body">
              {{ message }}
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    <!-- Scripts necesarios -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7/z9jdq1TCU6MscWbzqvKysf2b7suR8oFmf4eg60SxF0av/J7V96pHtB/c7v4j1p" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9b+AxRvZzsKnDgNA5PQmvFV3f5b5xpkir16ltTnvF57L9YJpvjhEe9e" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
     <script src="{% static 'js/finanzas.js' %}"></script>
     <script src="{% static 'js/mediopago.js' %}"></script>
     <script src="{% static 'js/global.js' %}"></script>
</body>
</html>

core/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle js-sidebar-toggle">
        <i class="hamburger align-self-center"></i>
    </a>
    {% if request.resolver_match.namespace == 'finanzas' %}
        <li class="nav-item d-flex align-items-left ms-4">
            <span class="text-success small me-2">Cotización Dólar:</span>  <!-- Mostrar el último precio -->
            <form method="post" action="{% url 'finanzas:actualizar_cotizacion' %}" class="form-inline d-flex">
                {% csrf_token %}
                <input type="number" name="valor_cotizacion" value="{{ cotizacion_actual }}" class="form-control form-control-sm me-2" required style="width: 80px;" readonly>
                <button type="button" class="btn btn-sm btn-orange me-2" id="edit-button">
                    <i class="fas fa-pencil-alt"></i>  <!-- Ícono de lápiz para editar -->
                </button>
                <button type="submit" class="btn btn-sm btn-success" id="submit-button" style="display: none;">
                    Actualizar
                </button>
            </form>
        </li>
    {% endif %}
    
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav me-auto">
        </ul>
        <ul class="navbar-nav navbar-align">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">
                    {% if request.user.foto %}
                        <img src="{{ request.user.foto.url }}" class="avatar img-fluid rounded me-2" alt="Foto de perfil">
                    {% else %}
                        <img src="{% static 'favicon.ico' %}" class="avatar img-fluid rounded me-2" alt="Foto de perfil por defecto">
                    {% endif %}
                    <span class="text-dark">{{ request.user.nombre }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a class="dropdown-item" href= "{% url 'perfil' %}"><i class="align-middle me-1" data-feather="user"></i> Perfil</a>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="pie-chart"></i> Análisis</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="settings"></i> Configuración</a>
                    <a class="dropdown-item" href="#"><i class="align-middle me-1" data-feather="help-circle"></i> Ayuda</a>
                    <div class="dropdown-divider"></div>
                    <form method="post" action="{% url 'logout' %}" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item">Cerrar sesión</button>
                    </form>
                </div>
            </li>
        </ul>
    </div>
</nav>

core/templates/sidebar.html
{% load static %}
<!-- Inicio del Sidebar -->
<div class="sidebar">
    <div class="sidebar-content js-simplebar">
        <a class="sidebar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/logoblanco.png' %}" alt="Logo Flipping Cars" style="width: 80%; height: auto;">
        </a>
        
        <li class="sidebar-item" style="margin-top: 2rem;">
            <a data-bs-target="#finanzas-dropdown" data-bs-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
                <i class='fas fa-chart-line' style='font-size:2vh'></i>
                <span class="align-middle" style="margin-left: 1vh;">Finanzas</span>
                <span class="arrow align-middle" style="float: right;">&#9662;</span>
            </a>
            <ul id="finanzas-dropdown" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                <li class="sidebar-item"><a class="sidebar-link" href="{% url 'finanzas:home' %}">Inicio</a></li>
                <li class="sidebar-item"><a class="sidebar-link" href="{% url 'finanzas:lista_movimientos' %}">Lista de Movimientos</a></li>
                <li class="sidebar-item"><a class="sidebar-link" href="{% url 'finanzas:crear_categoria' %}">Crear Categoria</a></li>
                <li class="sidebar-item"><a class="sidebar-link" href="{% url 'finanzas:crear_mediodepago' %}">Crear Medio de Pago</a></li>
                <li class="sidebar-item"><a class="sidebar-link" href="{% url 'finanzas:crear_movimiento' %}">Crear Movimiento</a></li>
            </ul>
        </li>
        <li class="sidebar-item">
            <a data-bs-target="#leads-dropdown" data-bs-toggle="collapse" class="sidebar-link collapsed" aria-expanded="false">
                <i class='fas fa-car' style='font-size:24px'></i>
                <span class="align-middle" style="margin-left: 1vh;">Autos</span>
                <span class="arrow align-middle" style="float: right;">&#9662;</span>
            </a>
            <ul id="leads-dropdown" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                <li class="sidebar-item"><a class="sidebar-link">Inicio</a></li>
                <li class="sidebar-item"><a class="sidebar-link">Lista de Movimientos</a></li>
                <li class="sidebar-item"><a class="sidebar-link">Crear Movimiento</a></li>
                <li class="sidebar-item"><a class="sidebar-link">Crear Categoria</a></li>
                <li class="sidebar-item"><a class="sidebar-link">Crear Medio de Pago</a></li>
            </ul>
        </li>
    </div>
</div>
<!-- Fin del Sidebar -->