core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('finanzas/', include('finanzas.urls')),
    path('', views.home),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.error_403_view

core/finanzas/urls.py
from django.urls import path
from . import views
from .views import eliminar_medio_pago, eliminar_categoria  # Asegúrate de importar la vista


app_name = 'finanzas'
urlpatterns = [
    path('', views.home_finanzas, name='home'),
    path('movimientos/', views.lista_movimientos, name='lista_movimientos'),
    path('movimientos/crear/', views.crear_movimiento, name='crear_movimiento'),
    path('categorias/crear/', views.crear_categoria, name='crear_categoria'),
    path('mediosdepago/crear/', views.crear_mediopago, name='crear_mediodepago'),
    path('mediopago/eliminar/<int:medio_pago_id>/', eliminar_medio_pago, name='eliminar_medio_pago'),
    path('categorias/eliminar/<int:id>/', eliminar_categoria, name='eliminar_categoria'), 
    path('movimientos/detalle/<int:id>/', views.detalle_movimiento, name='detalle_movimiento'),
    path('mediopagos/detalle/<int:medio_pago_id>/', views.detalle_medio_pago, name='detalle_medio_pago'),
    path('actualizar-cotizacion/', views.actualizar_cotizacion, name='actualizar_cotizacion'),
    path('eliminar-movimiento/<int:movimiento_id>/', views.eliminar_movimiento, name='eliminar_movimiento'),
    path('movimientos/editar/<int:movimiento_id>/', views.editar_movimiento, name='editar_movimiento'),  
    path('documento-adjunto/<int:documento_id>/eliminar/', views.eliminar_documento_adjunto, name='eliminar_documento_adjunto'),


]

core/finanzas/models.py
from django.db import models
from django.core.exceptions import ValidationError
from datetime import date
from django.conf import settings


class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    requiere_patente = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

    def __str__(self):
        return self.nombre

class MedioPago(models.Model):
    MONEDA_CHOICES = [
        ('USD', 'Dólares'),
        ('PESOS', 'Pesos'),
    ]
    nombre = models.CharField(max_length=100)
    moneda = models.CharField(max_length=10, choices=MONEDA_CHOICES)
    def __str__(self):
        return self.nombre

class Movimiento(models.Model):
    TIPO_CHOICES = [
        ('INGRESO', 'Ingreso'),
        ('SALIDA', 'Salida'),
    ]

    MONEDA_CHOICES = [
        ('USD', 'Dólares'),
        ('PESOS', 'Pesos'),
    ]


    fecha = models.DateField(default=date.today)

    tipo = models.CharField(max_length=10, choices=TIPO_CHOICES)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    detalles = models.TextField(blank=True, null=True)
    monto = models.DecimalField(max_digits=12, decimal_places=2)
    moneda = models.CharField(max_length=10, choices=MONEDA_CHOICES)
    comentario = models.TextField(blank=True, null=True)
    patente = models.CharField(max_length=10, blank=True, null=True)
    medio_pago = models.ForeignKey(MedioPago, on_delete=models.CASCADE)
    numero_comprobante = models.CharField(max_length=50, blank=True, null=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    precio_dolar = models.DecimalField(max_digits=12, decimal_places=2, editable=False)
    precio_peso = models.DecimalField(max_digits=12, decimal_places=2, editable=False)

    def __str__(self):
        return f"{self.tipo} - {self.categoria.nombre} - {self.monto} {self.moneda}"

    def clean(self):
        super().clean()
        if self.categoria.requiere_patente and not self.patente:
            raise ValidationError({'patente': 'Este campo es obligatorio para la categoría seleccionada.'})

    def save(self, *args, **kwargs):
        # Obtener la última cotización del dólar disponible
        from .models import CotizacionDolar  # Importación interna para evitar problemas de dependencia circular
        try:
            ultima_cotizacion = CotizacionDolar.objects.latest('fecha')
            cotizacion = ultima_cotizacion.valor_cotizacion
        except CotizacionDolar.DoesNotExist:
            raise ValidationError('No hay una cotización del dólar disponible.')

        # Calcular el precio en dólares y en pesos según la moneda seleccionada
        if self.moneda == 'USD':
            self.precio_dolar = self.monto
            self.precio_peso = self.monto * cotizacion
        elif self.moneda == 'PESOS':
            self.precio_peso = self.monto
            self.precio_dolar = self.monto / cotizacion

        super().save(*args, **kwargs)



class CotizacionDolar(models.Model):
    fecha = models.DateTimeField(unique=True, auto_now_add=True)
    valor_cotizacion = models.PositiveIntegerField()

    def __str__(self):
        return f'Cotización del {self.fecha}: {self.valor_cotizacion}'
    


class DocumentoAdjunto(models.Model):
    movimiento = models.ForeignKey(Movimiento, related_name='documentos_adjuntos', on_delete=models.CASCADE)
    archivo = models.FileField(upload_to='finanzas/documentos_adjuntos/')

    def __str__(self):
        return f"Documento para Movimiento {self.movimiento.id}"

core/finanzas/forms.py
from django import forms
from .models import Movimiento, Categoria, MedioPago, CotizacionDolar

class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        fields = ['fecha', 'tipo', 'categoria', 'detalles', 'monto', 'moneda', 'comentario', 'patente', 'medio_pago', 'numero_comprobante']

    def __init__(self, *args, **kwargs):
        super(MovimientoForm, self).__init__(*args, **kwargs)
        self.fields['patente'].required = False
        self.fields['fecha'].widget = forms.DateInput(attrs={'type': 'date'})
        self.fields['fecha'].required = True


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'requiere_patente']

class MedioPagoForm(forms.ModelForm):
    class Meta:
        model = MedioPago
        fields = ['nombre', 'moneda']
        
        
class CotizacionDolarForm(forms.ModelForm):
    class Meta:
        model = CotizacionDolar
        fields = ['valor_cotizacion']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['valor_cotizacion'].label = "Cotización del Dólar"

core/finanzas/views.py
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404  # Añadir esta línea
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages  # Agregar esta línea para importar messages
from .models import Movimiento, Categoria, MedioPago, CotizacionDolar, DocumentoAdjunto
from .forms import MovimientoForm, CategoriaForm, MedioPagoForm, CotizacionDolarForm
from django.db.models import Sum  # Add this line to import Sum
from .utils import filtrar_movimientos_por_fecha, calcular_totales, calcular_totales_por_medio_pago
from django.utils import timezone
from datetime import datetime

from datetime import datetime

@login_required
@permission_required('finanzas.view_movimiento', raise_exception=True)
def home_finanzas(request):
    # Filtrar los movimientos según el rango de fechas
    movimientos, start_date_str, end_date_str = filtrar_movimientos_por_fecha(request)
    
    # Formatear las fechas para mostrar en el formato "dd/mm/yyyy"
    start_date_formatted = None
    end_date_formatted = None

    if start_date_str:
        start_date_formatted = datetime.strptime(start_date_str, "%Y-%m-%d").strftime("%d/%m/%Y")
    if end_date_str:
        end_date_formatted = datetime.strptime(end_date_str, "%Y-%m-%d").strftime("%d/%m/%Y")

    # Obtener los últimos 5 movimientos ordenados por fecha descendente (sin filtrar)
    recent_movements = Movimiento.objects.all().order_by('-fecha')[:5]

    # Calcular totales sin decimales dentro del filtro
    totales = calcular_totales(movimientos)

    # Calcular totales por medio de pago dentro del filtro
    totales_medio_pago = calcular_totales_por_medio_pago(movimientos)

    # Obtener la última cotización del dólar
    try:
        ultima_cotizacion = CotizacionDolar.objects.latest('fecha')
        cotizacion_actual = ultima_cotizacion.valor_cotizacion
    except CotizacionDolar.DoesNotExist:
        cotizacion_actual = 0  # O un valor por defecto

    # Determinar los textos según si hay filtro de fecha aplicado o no
    if start_date_formatted and end_date_formatted:
        ingresos_pesos_label = f"Entradas de pesos\nDesde: {start_date_formatted}\nHasta: {end_date_formatted}"
        salidas_pesos_label = f"Salidas de pesos\nDesde: {start_date_formatted}\nHasta: {end_date_formatted}"
        ingresos_dolares_label = f"Entradas de dólares\nDesde: {start_date_formatted}\nHasta: {end_date_formatted}"
        salidas_dolares_label = f"Salidas de dólares\nDesde: {start_date_formatted}\nHasta: {end_date_formatted}"
    else:
        ingresos_pesos_label = "Entradas de pesos\nHistórico"
        salidas_pesos_label = "Salidas de pesos\nHistórico"
        ingresos_dolares_label = "Entradas de dólares\nHistórico"
        salidas_dolares_label = "Salidas de dólares\nHistórico"

    context = {
        'recent_movements': recent_movements,
        'total_ingresos_pesos': totales['total_ingresos_pesos'],
        'total_salidas_pesos': totales['total_salidas_pesos'],
        'total_ingresos_dolares': totales['total_ingresos_dolares'],
        'total_salidas_dolares': totales['total_salidas_dolares'],
        'start_date': start_date_str if start_date_str else '',
        'end_date': end_date_str if end_date_str else '',
        'totales_medio_pago': totales_medio_pago,
        'cotizacion_actual': cotizacion_actual,
        'ingresos_pesos_label': ingresos_pesos_label,
        'salidas_pesos_label': salidas_pesos_label,
        'ingresos_dolares_label': ingresos_dolares_label,
        'salidas_dolares_label': salidas_dolares_label,
        'start_date_formatted': start_date_formatted,
        'end_date_formatted': end_date_formatted,
    }

    return render(request, 'finanzas/home.html', context)





@login_required
@permission_required('finanzas.view_movimiento', raise_exception=True)
def lista_movimientos(request):
    categoria_id = request.GET.get('categoria')  # Obtener el ID de la categoría del query string
    fecha_inicio = request.GET.get('fecha_inicio')  # Obtener la fecha de inicio del query string
    fecha_fin = request.GET.get('fecha_fin')  # Obtener la fecha de fin del query string

    # Filtrar por fechas si están presentes
    if fecha_inicio and fecha_fin:
        movimientos = Movimiento.objects.filter(fecha__range=[fecha_inicio, fecha_fin]).order_by('-fecha')
    elif categoria_id:
        movimientos = Movimiento.objects.filter(categoria_id=categoria_id).order_by('-fecha')  # Filtrar por categoría
    else:
        movimientos = Movimiento.objects.all().order_by('-fecha')
        
    categorias = Categoria.objects.all()  # Obtener las categorías para el contexto
    medios_pago = MedioPago.objects.all()  # Obtener los medios de pago para el contexto
    return render(request, 'finanzas/lista_movimientos.html', {
        'movimientos': movimientos,
        'categorias': categorias,
        'medios_pago': medios_pago  # Asegúrate de pasar los medios de pago
    })

# views.py
@login_required
@permission_required('finanzas.add_movimiento', raise_exception=True)
def crear_movimiento(request):
    # Verificar si se ha actualizado la cotización del dólar hoy
    today = timezone.now().date()
    cotizacion_actualizada_hoy = CotizacionDolar.objects.filter(fecha__date=today).exists()

    if request.method == 'POST':
        form = MovimientoForm(request.POST, request.FILES)
        if form.is_valid():
            movimiento = form.save(commit=False)
            movimiento.usuario = request.user  # Asocia el movimiento al usuario actual
            movimiento.save()

            # Guardar los archivos adjuntos
            for archivo in request.FILES.getlist('archivos'):
                DocumentoAdjunto.objects.create(movimiento=movimiento, archivo=archivo)

            messages.success(request, 'Movimiento creado exitosamente.')
            return redirect('finanzas:lista_movimientos')
    else:
        form = MovimientoForm()

    # Agregar medios de pago y categorías al contexto
    categorias = Categoria.objects.all()
    medios_pago = MedioPago.objects.all()

    context = {
        'form': form,
        'categorias': categorias,
        'medios_pago': medios_pago,
        'cotizacion_actualizada_hoy': cotizacion_actualizada_hoy,
    }

    return render(request, 'finanzas/crear_movimiento.html', context)





@login_required
@permission_required('finanzas.add_movimiento', raise_exception=True)
def crear_categoria(request):
    if request.method == 'POST':
        nombre = request.POST.get('nueva_categoria')
        requiere_patente = 'requiere_patente' in request.POST
        if nombre:
            Categoria.objects.create(nombre=nombre, requiere_patente=requiere_patente)
        return redirect('finanzas:crear_categoria')
    categorias = Categoria.objects.all()
    return render(request, 'finanzas/crear_categoria.html', {'categorias': categorias})


@login_required
@permission_required('finanzas.add_movimiento', raise_exception=True)
def crear_mediopago(request):
       if request.method == 'POST':
           form = MedioPagoForm(request.POST)
           if form.is_valid():
               form.save()
               return redirect('finanzas:crear_mediodepago')
           else:
               # Agregar un mensaje de error
               messages.error(request, 'Error al crear el medio de pago. Verifica los datos.')
       else:
           form = MedioPagoForm()
       medios_pago = MedioPago.objects.all()
       return render(request, 'finanzas/crear_mediodepago.html', {'form': form, 'medios_pago': medios_pago})


@login_required
@permission_required('finanzas.delete_mediopago', raise_exception=True)
def eliminar_medio_pago(request, medio_pago_id):
    medio_pago = get_object_or_404(MedioPago, id=medio_pago_id)  # Obtener el medio de pago
    medio_pago.delete()  # Eliminar el medio de pago
    messages.success(request, 'Medio de pago eliminado con éxito.')  # Mensaje de éxito
    return redirect('finanzas:crear_mediodepago')  # Redirigir a la vista deseada


@login_required
@permission_required('finanzas.view_movimiento', raise_exception=True)
def detalle_movimiento(request, id):
    movimiento = get_object_or_404(Movimiento, id=id)
    return render(request, 'finanzas/detalle_movimiento.html', {'movimiento': movimiento})


@login_required
@permission_required('finanzas.delete_categoria', raise_exception=True)  # Asegúrate de tener el permiso correcto
def eliminar_categoria(request, id):
    categoria = get_object_or_404(Categoria, id=id)  # Obtener la categoría
    categoria.delete()  # Eliminar la categoría
    messages.success(request, 'Categoría eliminada con éxito.')  # Mensaje de éxito
    return redirect('finanzas:crear_categoria')  # Redirigir a la vista deseada


@login_required
@permission_required('finanzas.view_movimiento', raise_exception=True)
def detalle_medio_pago(request, medio_pago_id):
    # Obtener el medio de pago o devolver 404 si no existe
    medio_pago = get_object_or_404(MedioPago, id=medio_pago_id)
    
    # Obtener todos los movimientos asociados a este medio de pago, ordenados por fecha descendente
    movimientos = Movimiento.objects.filter(medio_pago=medio_pago).select_related('categoria').order_by('-fecha')
    
    # Calcular totales para mostrar en la plantilla
    total_ingresos = movimientos.filter(tipo='INGRESO').aggregate(total=Sum('monto'))['total'] or 0
    total_salidas = movimientos.filter(tipo='SALIDA').aggregate(total=Sum('monto'))['total'] or 0
    total_neto = int(total_ingresos) - int(total_salidas)
    
    context = {
        'medio_pago': medio_pago,
        'movimientos': movimientos,
        'total_ingresos': total_ingresos,
        'total_salidas': total_salidas,
        'total_neto': total_neto,
    }
    
    return render(request, 'finanzas/detalle_medio_pago.html', context)


@login_required
@permission_required('finanzas.add_movimiento', raise_exception=True)
def actualizar_cotizacion(request):

core/finanzas/templates/finanzas/crear_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-4">
        <h2 class="text-center mb-4">Crear Nueva Categoría</h2>
        <!-- Formulario para agregar nueva categoría -->
        <form method="post" action="{% url 'finanzas:crear_categoria' %}" class="mb-4 mx-auto" style="max-width: 500px;">
            {% csrf_token %}
            <div class="mb-3">
                <label for="nueva_categoria" class="form-label">Nombre de la Nueva Categoría</label>
                <input type="text" class="form-control" id="nueva_categoria" name="nueva_categoria" required>
            </div>
            <div class="form-check mb-3">
                <input type="checkbox" class="form-check-input" id="requiere_patente" name="requiere_patente">
                <label for="requiere_patente" class="form-check-label">Requiere Patente</label>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Agregar Categoría</button>
            </div>
        </form>

        <h3 class="text-center mb-4">Categorías Existentes</h3>
        <div class="d-flex justify-content-center">
            <ul class="list-group" style="max-width: 600px; width: 100%;">
                {% for categoria in categorias %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <span>{{ categoria.nombre }}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

core/finanzas/templates/finanzas/detalle_medio_pago.html
<!-- finanzas/templates/finanzas/detalle_medio_pago.html -->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de Medio de Pago - {{ medio_pago.nombre }}</title>
    <link href="{% static 'css/finanzas.css' %}" rel="stylesheet">
    <!-- FontAwesome para los íconos -->
    <script src="{% static 'js/mediopago.js' %}" defer></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.3.0/exceljs.min.js"></script>
</head>
<body>
    <div class="row mb-2 mb-xl-3 align-items-center mx-2"> <!-- Añadido mx-2 para agregar un borde a los lados -->
        <div class="col-auto d-flex align-items-center">
            <h3 class="mb-0 me-3 fechashome"><strong>Detalle de {{ medio_pago.nombre }}</strong></h3>
            <a href="{% url 'finanzas:home' %}" class="btn btn-primary btn-sm">Inicio</a>
        </div>
        <div class="col-auto ms-auto text-center">
            <!-- Grupo de Botones para pantallas grandes -->
            <div class="btn-group d-none d-md-flex">
                <a href="{% url 'finanzas:lista_movimientos' %}" class="btn btn-primary btn-sm">Lista de Movimientos</a>
                <a href="{% url 'finanzas:crear_categoria' %}" class="btn btn-white-custom btn-sm">Crear Categoría</a>
                <a href="{% url 'finanzas:crear_movimiento' %}" class="btn btn-white-custom btn-sm">Crear Movimiento</a>
                <a href="{% url 'finanzas:crear_mediodepago' %}" class="btn btn-white-custom btn-sm">Crear Medio de Pago</a>
            </div>
            <!-- Dropdown de acciones para pantallas pequeñas -->
            <div class="d-md-none mt-3 text-center"> <!-- Añadido text-center para centrar el dropdown -->
                <div class="btn-group w-100">
                    <button class="btn btn-primary btn-sm dropdown-toggle btn-acciones-mobile" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Acciones
                    </button>
                    <ul class="dropdown-menu w-150">
                        <li><a class="dropdown-item" href="{% url 'finanzas:lista_movimientos' %}">Lista de Movimientos</a></li>
                        <li><a class="dropdown-item" href="{% url 'finanzas:crear_categoria' %}">Crear Categoría</a></li>
                        <li><a class="dropdown-item" href="{% url 'finanzas:crear_movimiento' %}">Crear Movimiento</a></li>
                        <li><a class="dropdown-item" href="{% url 'finanzas:crear_mediodepago' %}">Crear Medio de Pago</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Información del Medio de Pago y Totales -->
<!-- Información del Medio de Pago y Totales -->
<div class="col-12 mb-4">
    <div class="card payment-info-card shadow-sm">
        <div class="card-body">
            <h4 class="card-title payment-title">{{ medio_pago.nombre }}</h4>
            <div class="card-text payment-details">
                <div class="payment-item">
                    <strong>Total Ingresos:</strong>
                    <span class="payment-value text-success">{{ total_ingresos }}</span>
                </div>
                <div class="payment-item">
                    <strong>Total Salidas:</strong>
                    <span class="payment-value text-danger">{{ total_salidas }}</span>
                </div>
                <div class="payment-item">
                    <strong>Total Neto:</strong>
                    {% if total_neto > 0 %}
                        <span class="payment-value text-success">{{ total_neto }}</span>
                    {% elif total_neto < 0 %}
                        <span class="payment-value text-danger">{{ total_neto }}</span>
                    {% else %}
                        <span class="payment-value text-secondary">{{ total_neto }}</span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

        <!-- Tabla de Movimientos del Medio de Pago -->
        <div class="col-12">
            <div class="card flex-fill w-90">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="card-title mb-0">Movimientos de {{ medio_pago.nombre }}</h5>
                    <button id="exportarExcelMedioPago" class="btn btn-success" style="width: 150px; height: 4vh;">
                        <i class="fas fa-file-export"></i> Exportar a Excel
                    </button>
                </div>
                <div class="card-body pt-2 pb-3">
                    <div class="table-responsive">
                        <table  class="table table-hover table-bordered my-0 w-100">
                            <thead class="table-light">
                                <tr>
                                    <th>Fecha</th>
                                    <th>Tipo</th>
                                    <th>Categoría</th>
                                    <th>Monto</th>
                                    <th>Moneda</th>
                                    <th>Patente</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for movimiento in movimientos %}
                                <tr>
                                    <td>{{ movimiento.fecha|date:"j/n/Y" }}</td>
                                    <td>
                                        <span class="tipo-label {{ movimiento.tipo|lower }}">{{ movimiento.get_tipo_display }}</span>
                                    </td>
                                    <td>{{ movimiento.categoria.nombre }}</td>
                                    <td>{{ movimiento.monto }}</td>
                                    <td>{{ movimiento.get_moneda_display }}</td>
                                    <td>{{ movimiento.patente|default:"-" }}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="6" class="text-center">No hay movimientos para este medio de pago.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

core/finanzas/templates/finanzas/detalle_movimiento.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <h2 class="text-center mb-4">Detalle del Movimiento</h2>
        <div class="card p-4 shadow-sm detalle-movimiento-card" id="movimiento-detalle">
            <div class="row mb-3">
                <!-- Primera columna de información -->
                <div class="col-md-6 detalle-col">
                    <p><strong>Fecha:</strong> <span class="detalle-info">{{ movimiento.fecha|date:"j/n/Y" }}</span></p>
                    <p><strong>Tipo:</strong> <span class="tipo-label {{ movimiento.tipo|lower }}">{{ movimiento.tipo }}</span></p>
                    <p><strong>Categoría:</strong> <span class="detalle-info">{{ movimiento.categoria.nombre }}</span></p>
                    <p><strong>Detalles:</strong> <span class="detalle-info">{{ movimiento.detalles }}</span></p>
                    <p><strong>Monto:</strong> <span class="detalle-info">{{ movimiento.monto }}</span></p>
                    <p><strong>Moneda:</strong> <span class="detalle-info">{{ movimiento.moneda }}</span></p>
                    {% if movimiento.moneda == 'USD' %}
                    <p><strong>Precio en Pesos:</strong> <span class="detalle-info">{{ movimiento.precio_peso }}</span></p>
                    {% elif movimiento.moneda == 'PESOS' %}
                    <p><strong>Precio en Dólares:</strong> <span class="detalle-info">{{ movimiento.precio_dolar }}</span></p>
                    {% endif %}
                </div>
                <!-- Segunda columna de información -->
                <div class="col-md-6 detalle-col">
                    <p><strong>Comentario:</strong> <span class="detalle-info">{{ movimiento.comentario }}</span></p>
                    <p><strong>Patente:</strong> <span class="detalle-info">{{ movimiento.patente }}</span></p>
                    <p><strong>Medio de Pago:</strong> <span class="detalle-info">{{ movimiento.medio_pago.nombre }}</span></p>
                    <p><strong>Número de Comprobante:</strong> <span class="detalle-info">{{ movimiento.numero_comprobante }}</span></p>
                    {% if movimiento.documento_adjunto %}
                    <div class="mb-3">
                        <p><strong>Documento Adjunto:</strong></p>
                        <a href="{{ movimiento.documento_adjunto.url }}" class="btn btn-outline-primary" target="_blank">Ver Documento</a>
                    </div>
                    {% endif %}
                    {% if movimiento.documentos_adjuntos.exists %}
                    <div class="mb-3">
                        <p><strong>Documentos Adjuntos:</strong></p>
                        {% for documento in movimiento.documentos_adjuntos.all %}
                        <a href="{{ documento.archivo.url }}" class="btn btn-outline-primary mb-1" target="_blank">Ver Documento {{ forloop.counter }}</a>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="text-center">
                <button id="download-pdf" class="btn btn-primary btn-sm">Descargar PDF</button>
                {{ edit_1 }}
                <a id="editar_movimiento" href="{% url 'finanzas:editar_movimiento' movimiento.id %}" class="btn btn-success btn-sm mx-1">Editar Movimiento <i class="fas fa-pencil-alt"></i></a>
                {{ edit_2 }}
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script>
        document.getElementById('download-pdf').addEventListener('click', function() {
            const element = document.getElementById('movimiento-detalle');
            const downloadButton = document.getElementById('download-pdf');
            const editButton = document.getElementById('editar_movimiento'); // Asegúrate de que el ID sea correcto
    
            // Añadir clase para ocultar botones
            if (editButton) editButton.classList.add('d-none');
            downloadButton.classList.add('d-none');
    
            html2pdf()
                .from(element)
                .set({
                    margin: 1,
                    filename: 'comprobante_pago.pdf',
                    html2canvas: { scale: 2 },
                    jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
                })
                .save()
                .then(() => {
                    // Remover clase para mostrar los botones nuevamente
                    if (editButton) editButton.classList.remove('d-none');
                    downloadButton.classList.remove('d-none');
                });
        });
    </script>
{% endblock %}